# generated by datamodel-codegen:
#   filename:  dcp.yaml
#   timestamp: 2026-05-20T11:06:02+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import AnyUrl, BaseModel, EmailStr, Extra, Field


class Error1(BaseModel):
    code: str | None = None
    message: str | None = None


class Error(BaseModel):
    error: str | Error1


class SuccessResponse(BaseModel):
    success: bool


class Pagination(BaseModel):
    page: int
    limit: int
    total: int
    pages: int


class Error2(BaseModel):
    message: str
    type: str = Field(
        ...,
        description='OpenAI-style error type (e.g. invalid_request_error, server_error).',
    )
    code: str | None = None
    status: int | None = None
    retryable: bool | None = None
    details: dict[str, Any] | None = None


class V1Error(BaseModel):
    error: Error2


class Alternative(BaseModel):
    model: str
    reason: str | None = None
    provider_count: int | None = None


class Error3(BaseModel):
    message: str
    type: str = Field(
        ...,
        description='OpenAI-style error type (e.g. invalid_request_error, server_error).',
    )
    code: str | None = None
    status: int | None = None
    retryable: bool | None = None
    details: dict[str, Any] | None = None
    alternatives: list[Alternative] | None = None


class V1ModelUnavailableError(V1Error):
    error: Error3 | None = None


class Object(Enum):
    list = 'list'


class Object1(Enum):
    model = 'model'


class Architecture(BaseModel):
    tokenizer: str | None = None
    instruct_type: str | None = None
    modality: str | None = None


class Endpoint(BaseModel):
    url: str | None = None
    type: str | None = None


class ModelPricing(BaseModel):
    prompt_tokens: str | None = Field(
        None, description='USD per token, stringified for precision.'
    )
    completion_tokens: str | None = None
    usd_per_minute: str | None = None
    usd_per_1m_input_tokens: str | None = None
    usd_per_1m_output_tokens: str | None = None


class Role(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class Type(Enum):
    function = 'function'


class Function(BaseModel):
    name: str
    arguments: str


class ToolCall(BaseModel):
    id: str
    type: Type
    function: Function


class Object2(Enum):
    chat_completion = 'chat.completion'


class Usage(BaseModel):
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = None


class RenterRegisterRequest(BaseModel):
    name: str = Field(..., max_length=120)
    email: EmailStr
    organization: str | None = Field(None, max_length=160)
    use_case: str | None = Field(None, max_length=120)
    phone: str | None = Field(None, max_length=40)


class Next(Enum):
    check_email = 'check_email'


class RenterRegisterAccepted(BaseModel):
    success: bool
    next: Next
    email: str
    renter_id: int
    message: str | None = None


class Renter(BaseModel):
    id: int
    name: str
    email: EmailStr
    organization: str | None = None
    use_case: str | None = None
    phone: str | None = None
    webhook_url: str | None = None
    balance_halala: int = Field(
        ..., description='Balance in Saudi halala (1 SAR = 100 halala).'
    )
    total_spent_halala: int | None = None
    total_jobs: int | None = None
    created_at: datetime | None = None


class RenterV1UsageSummary(BaseModel):
    total_requests: int | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = None
    total_cost_halala: int | None = None


class RenterBalanceResponse(BaseModel):
    balance_halala: int
    balance_sar: float
    held_halala: int
    held_sar: float
    available_halala: int
    total_spent_halala: int
    total_spent_sar: float
    total_jobs: int


class RenterTopupRequest(BaseModel):
    amount_halala: int | None = Field(None, ge=1, le=100000)
    amount_sar: float | None = Field(None, ge=0.01, le=1000.0)


class RenterTopupResponse(BaseModel):
    success: bool
    topped_up_halala: int
    topped_up_sar: float
    new_balance_halala: int
    new_balance_sar: float


class Status(Enum):
    pending = 'pending'
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class RenterJobSummary(BaseModel):
    id: int
    job_id: str | None = None
    job_type: str | None = None
    status: Status
    submitted_at: datetime | None = None
    completed_at: datetime | None = None
    actual_cost_halala: int | None = None


class RenterJobRow(BaseModel):
    job_id: str | None = None
    template_id: str | None = None
    provider_id: int | None = None
    status: str | None = None
    started_at: datetime | None = None
    completed_at: datetime | None = None
    cost_halala: int | None = None
    output_tokens: int | None = None
    input_tokens: int | None = None


class AllTime(BaseModel):
    total_jobs: int
    total_halala: int
    total_sar: float


class MonthlyItem(BaseModel):
    month: str = Field(..., description='YYYY-MM.')
    jobs: int
    total_halala: int


class Last30Day(BaseModel):
    date: date_aliased
    jobs: int
    total_halala: int


class RenterSpendingResponse(BaseModel):
    all_time: AllTime
    monthly: list[MonthlyItem]
    last_30_days: list[Last30Day]


class Scope(Enum):
    inference = 'inference'
    jobs_read = 'jobs.read'
    balance_read = 'balance.read'
    admin = 'admin'


class ScopedKeyCreateRequest(BaseModel):
    label: str | None = Field(None, max_length=80)
    scopes: list[Scope] | None = ['inference']
    expires_at: datetime | None = None
    org_role: str | None = None


class ScopedApiKey(BaseModel):
    id: str
    label: str | None = None
    scopes: list[str]
    org_id: str | None = None
    org_role: str | None = None
    expires_at: datetime | None = None
    last_used_at: datetime | None = None
    created_at: datetime
    revoked: bool


class ScopedApiKeyMinted(ScopedApiKey):
    key: str = Field(
        ...,
        description='The full secret. Returned exactly once; persisted only as a hash.\n',
    )


class Permission(Enum):
    inference = 'inference'
    jobs_read = 'jobs.read'
    balance_read = 'balance.read'


class DcpKeyCreateRequest(BaseModel):
    label: str | None = Field(None, max_length=80)
    permissions: list[Permission] | None = ['inference']
    org_role: str | None = None


class DcpKeyMinted(BaseModel):
    keyId: str
    key: str = Field(..., description='Returned exactly once.')
    label: str | None = None
    permissions: list[str]
    org_id: str | None = None
    org_role: str | None = None
    created_at: datetime


class RenterDcpKeyListItem(BaseModel):
    keyId: str
    label: str | None = None
    permissions: list[str]
    key_hint: str = Field(..., description='Format: `dcp_...XXXX` (last 4 chars only).')
    org_id: str | None = None
    org_role: str | None = None
    expires_at: datetime | None = None
    last_used_at: datetime | None = None
    created_at: datetime
    revoked: bool


class Direction(Enum):
    credit = 'credit'
    debit = 'debit'


class LedgerEntry(BaseModel):
    id: str
    direction: Direction
    amount_halala: int
    amount_sar: float | None = None
    description: str | None = None
    job_id: str | None = None
    created_at: datetime


class LedgerPage(BaseModel):
    entries: list[LedgerEntry]
    total: int | None = None
    limit: int | None = None
    offset: int | None = None


class Event(Enum):
    job_completed = 'job.completed'
    job_failed = 'job.failed'
    balance_low = 'balance.low'


class RenterWebhook(BaseModel):
    id: str
    url: AnyUrl
    events: list[Event]
    active: bool
    created_at: datetime


class RenterWebhookCreate(BaseModel):
    url: AnyUrl = Field(
        ..., description='HTTPS-only, port 443, public host (SSRF-checked).'
    )
    secret: str = Field(
        ..., description='HMAC signing secret (>= 16 chars).', min_length=16
    )
    events: list[Event] | None = None


class ProviderRegisterRequest(BaseModel):
    name: str = Field(..., max_length=120)
    email: EmailStr
    gpu_model: str = Field(..., max_length=120)
    os: str = Field(..., description='Normalized OS (linux/windows/macos).')
    phone: str | None = Field(None, max_length=40)
    location: str | None = Field(None, max_length=200)
    resource_spec: dict[str, Any] | str | None = None


class ProviderRegisterResponse(BaseModel):
    success: bool
    provider_id: int
    api_key: str = Field(..., description='`dcp-provider-…` — keep secret.')
    installer_url: str = Field(
        ..., description='Canonical setup download path (relative).'
    )
    message: str | None = None


class HeartbeatRequest(BaseModel):
    class Config:
        extra = Extra.allow

    gpu_utilization_pct: float | None = Field(None, ge=0.0, le=100.0)
    gpu_utilization: float | None = Field(
        None, description='Legacy alias for gpu_utilization_pct.'
    )
    vram_used_mb: int | None = Field(None, ge=0)
    vram_used: int | None = Field(None, description='Legacy alias for vram_used_mb.')
    vram_total_mb: int | None = None
    vram_total: int | None = Field(None, description='Legacy alias for vram_total_mb.')
    active_jobs: int | None = None
    jobs_active: int | None = Field(None, description='Legacy alias.')
    jobs_running: int | None = Field(None, description='Legacy alias.')
    uptime_seconds: int | None = None
    model_loaded: str | None = Field(
        None, description='Currently loaded model identifier.'
    )


class Status1(Enum):
    online = 'online'
    busy = 'busy'
    paused = 'paused'
    error = 'error'


class Kind(Enum):
    model_preload = 'model_preload'
    model_unload = 'model_unload'
    restart = 'restart'
    config_reload = 'config_reload'
    pull_model = 'pull_model'


class PendingTask(BaseModel):
    task_id: str
    kind: Kind
    payload: dict[str, Any] | None = None


class Vendor(Enum):
    nvidia = 'nvidia'
    amd = 'amd'
    apple = 'apple'
    intel = 'intel'


class Card(BaseModel):
    model: str | None = None
    vram_gb: float | None = None
    compute_capability: str | None = None


class GpuInfo(BaseModel):
    vendor: Vendor
    count: int = Field(..., ge=1)
    total_vram_gb: float
    cards: list[Card] | None = None


class Engine(Enum):
    ollama = 'ollama'
    vllm = 'vllm'
    llamacpp = 'llamacpp'


class ModelStatus(BaseModel):
    alias: str = Field(..., example='qwen3.6-27b-mtp')
    engine: Engine | None = None
    ready: bool
    port: int | None = None
    context_window: int | None = None


class LivenessStatus(Enum):
    online = 'online'
    stale = 'stale'
    offline = 'offline'


class ProviderLivenessResponse(BaseModel):
    provider_id: str
    liveness_status: LivenessStatus
    last_heartbeat: datetime | None = None
    heartbeat_age_seconds: int | None = None


class Period(Enum):
    field_1h = '1h'
    field_6h = '6h'
    field_24h = '24h'
    field_7d = '7d'


class ProviderMetricsRow(BaseModel):
    recorded_at: datetime
    gpu_utilization_pct: float | None = None
    vram_used_mb: int | None = None
    active_jobs: int | None = None


class Tier(Enum):
    A = 'A'
    B = 'B'
    C = 'C'


class ProviderBenchmarkRequest(BaseModel):
    gpu_model: str
    vram_gb: float = Field(..., ge=1.0, le=1000.0)
    tflops: float = Field(..., ge=1.0, le=10000.0)
    bandwidth_gbps: float = Field(..., ge=1.0, le=100000.0)
    tokens_per_sec: float = Field(..., ge=1.0, le=100000.0)
    tier: Tier | None = Field(
        None, description='Optional; auto-assigned by tflops + vram if absent.'
    )


class ProviderBenchmarkResponse(BaseModel):
    success: bool
    provider_id: int | str
    gpu_model: str
    tier: Tier
    timestamp: datetime
    message: str | None = None


class Status2(Enum):
    registered = 'registered'
    online = 'online'
    offline = 'offline'
    paused = 'paused'
    connected = 'connected'
    error = 'error'


class SupportedComputeType(Enum):
    inference = 'inference'
    training = 'training'
    rendering = 'rendering'


class GpuProfileSource(Enum):
    daemon = 'daemon'
    manual = 'manual'


class ApprovalStatus(Enum):
    pending = 'pending'
    approved = 'approved'
    rejected = 'rejected'


class GpuMetrics(BaseModel):
    utilization_pct: float | None = None
    vram_used_mib: int | None = None
    temperature_c: float | None = None


class ProviderActiveJob(BaseModel):
    id: int | None = None
    job_id: str | None = None
    job_type: str | None = None
    started_at: datetime | None = None
    cost_halala: int | None = None


class ProviderRecentJob(BaseModel):
    id: int | None = None
    job_id: str | None = None
    job_type: str | None = None
    model: str | None = None
    status: str | None = None
    submitted_at: datetime | None = None
    completed_at: datetime | None = None
    actual_cost_halala: int | None = None
    provider_earned_halala: int | None = None
    dc1_fee_halala: int | None = None


class ProviderStats(BaseModel):
    jobs_completed: int
    jobs_failed: int
    total_compute_minutes: float
    earnings_halala: int
    earnings_sar: float
    uptime_hours_last_7d: float
    avg_job_duration_minutes: float


class GpuRequirements(BaseModel):
    min_vram_gb: float | None = Field(None, ge=0.0, le=1024.0)
    gpu_type: str | None = None


class PricingClass(Enum):
    standard = 'standard'
    priority = 'priority'
    economy = 'economy'


class JobCreateRequest(BaseModel):
    job_type: str | None = Field(
        None,
        description='Required unless `template_id` resolves a job_type. Allowed values\nare enforced server-side (training/inference/render variants).\n',
    )
    template_id: str | None = Field(
        None, description='Docker template id; supplies job_type defaults.'
    )
    duration_minutes: float = Field(..., ge=0.01, le=1440.0)
    gpu_requirements: GpuRequirements | None = None
    params: dict[str, Any] | None = None
    pricing_class: PricingClass | None = 'standard'
    model: str | None = None
    provider_id: int | None = Field(None, description='Optional sticky-routing hint.')


class Provider(BaseModel):
    id: int | None = None
    name: str | None = None


class JobDispatchInfo(BaseModel):
    assigned: bool
    queued: bool
    hold_id: str | None = None
    provider: Provider | None = None


class Status3(Enum):
    pending = 'pending'
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class Job(BaseModel):
    id: int | None = None
    job_id: str
    job_type: str | None = None
    model: str | None = None
    status: Status3
    submitted_at: datetime | None = None
    started_at: datetime | None = None
    completed_at: datetime | None = None
    duration_minutes: float | None = None
    actual_duration_minutes: float | None = None
    cost_halala: int | None = None
    actual_cost_halala: int | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    provider_id: int | None = None
    renter_id: int | None = None
    pricing_class: str | None = None
    gpu_requirements: dict[str, Any] | None = None
    queue_position: int | None = Field(
        None, description='Present only when status = queued.'
    )
    elapsed_sec: int | None = None
    tokens_used: int | None = None
    cost_usd: float | None = None
    refunded_at: datetime | None = None


class JobWithBilling(Job):
    provider_name: str | None = None
    billing_id: str | None = None
    gross_cost_halala: int | None = None
    platform_fee_halala: int | None = None
    provider_earning_halala: int | None = None
    currency: str | None = None
    billing_status: str | None = None
    token_count: int | None = None
    duration_ms: int | None = None


class JobListRow(BaseModel):
    id: int | None = None
    job_id: str | None = None
    job_type: str | None = None
    template_name: str | None = None
    gpu_model: str | None = None
    status: str | None = None
    submitted_at: datetime | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    duration_seconds: float | None = None
    tokens_used: int | None = None
    cost_sar: str | None = Field(None, description='SAR formatted to 2 decimals.')
    refunded: bool | None = None


class JobStatusResponse(BaseModel):
    job_id: str
    status: str
    tokens_generated: int | None = None
    elapsed_seconds: int | None = None
    estimated_cost_usd: float | None = None
    provider_online: bool | None = None


class InsufficientBalanceError(BaseModel):
    error: str
    balance_halala: int | None = None
    required_halala: int | None = None
    shortfall_halala: int | None = None
    available_halala: int | None = None
    docs: str | None = None


class AgentManifest(BaseModel):
    safe_commit: str = Field(..., regex='^[0-9a-f]{40}$')
    rollout_pct: int = Field(..., ge=0, le=100)
    published_at: datetime
    min_tag: str | None = Field(
        None, description='Optional minimum semver tag.', example='v0.6.0'
    )


class Model(BaseModel):
    id: str
    object: Object1
    owned_by: str | None = None
    name: str | None = None
    description: str | None = None
    context_length: int | None = None
    pricing: ModelPricing | None = None
    architecture: Architecture | None = None
    endpoints: list[Endpoint] | None = None
    provider_priority: list[str] | None = None
    display_name: str | None = None
    context_window: int | None = None
    parameter_count: int | None = None


class ChatMessage(BaseModel):
    role: Role
    content: str | None = None
    name: str | None = None
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class Choice(BaseModel):
    index: int | None = None
    message: ChatMessage | None = None
    finish_reason: str | None = None


class ChatCompletionResponse(BaseModel):
    id: str
    object: Object2
    created: int
    model: str
    choices: list[Choice]
    usage: Usage | None = None
    x_dcp_provider_id: int | None = None
    x_dcp_routing: dict[str, Any] | None = None


class RenterMeResponse(BaseModel):
    renter: Renter
    recent_jobs: list[RenterJobSummary]
    v1_usage_summary: RenterV1UsageSummary | None = None


class RenterJobsPage(BaseModel):
    jobs: list[RenterJobRow]
    total: int
    page: int
    limit: int
    pages: int


class RenterBalanceWithLedger(BaseModel):
    balance_sar: float
    balance_halala: int
    balance_usd: float | None = None
    last_topup_at: datetime | None = None
    total_spent_sar: float | None = None
    recent_transactions: list[LedgerEntry]


class HeartbeatLegacyRequest(BaseModel):
    class Config:
        extra = Extra.allow

    api_key: str
    gpu_status: dict[str, Any] | None = None
    gpu_info: GpuInfo | None = None
    uptime: int | None = None
    provider_ip: str | None = None
    provider_hostname: str | None = None
    peer_id: str | None = None
    cached_models: list[str] | None = None
    resource_spec: dict[str, Any] | None = None
    vllm_endpoint_url: AnyUrl | None = None
    vllm_models: list[str] | None = None
    wg_mesh_ip: str | None = None
    wg_health: dict[str, Any] | None = None
    task_updates: list[dict[str, Any]] | None = None
    version: str | None = None
    status: Status1 | None = None
    models: list[ModelStatus] | None = None


class HeartbeatResponse(BaseModel):
    ok: bool | None = None
    success: bool | None = None
    provider_id: int | str | None = None
    status: str | None = None
    timestamp: datetime | None = None
    uptime_seconds: int | None = None
    model_loaded: str | None = None
    tasks: list[PendingTask] | None = None


class ProviderMetricsTimeseries(BaseModel):
    provider_id: str
    period: Period
    since: datetime
    count: int
    metrics: list[ProviderMetricsRow]


class ProviderProfile(BaseModel):
    id: int
    name: str
    status: Status2
    gpu_model: str
    gpu_vram_mib: int | None = None
    gpu_count_reported: int | None = None
    gpu_compute_capability: str | None = None
    gpu_cuda_version: str | None = None
    vram_mb: int | None = None
    gpu_count: int | None = None
    supported_compute_types: list[SupportedComputeType] | None = None
    gpu_profile_source: GpuProfileSource | None = None
    gpu_profile_updated_at: datetime | None = None
    auto_detected: bool | None = None
    resource_spec: dict[str, Any] | None = None
    last_heartbeat: datetime | None = None
    daemon_version: str | None = None
    run_mode: str | None = None
    scheduled_start: str | None = None
    scheduled_end: str | None = None
    wallet_address: str | None = None
    wallet_address_updated_at: datetime | None = None
    gpu_usage_cap_pct: int | None = None
    vram_reserve_gb: float | None = None
    temp_limit_c: int | None = None
    is_paused: bool | None = None
    approval_status: ApprovalStatus | None = None
    approved_at: datetime | None = None
    rejected_reason: str | None = None
    total_earnings_halala: int | None = None
    total_jobs: int | None = None
    uptime_percent: float | None = None
    gpu_metrics: GpuMetrics | None = None
    today_earnings_halala: int | None = None
    week_earnings_halala: int | None = None
    month_earnings_halala: int | None = None
    active_job: ProviderActiveJob | None = None


class ProviderMeMetricsResponse(BaseModel):
    provider_id: int
    gpu_model: str | None = None
    stats: ProviderStats
    recent_jobs: list[ProviderRecentJob] | None = None


class JobCreateResponse(BaseModel):
    success: bool
    job: Job
    dispatch: JobDispatchInfo
    idempotent: bool | None = None


class JobsListResponse(BaseModel):
    total: int
    limit: int
    offset: int
    jobs: list[JobListRow]


class ModelList(BaseModel):
    object: Object
    data: list[Model]


class ChatCompletionRequest(BaseModel):
    class Config:
        extra = Extra.allow

    model: str
    messages: list[ChatMessage] = Field(..., max_items=100, min_items=1)
    max_tokens: int | None = Field(512, ge=1, le=8192)
    temperature: float | None = Field(0.7, ge=0.0, le=2.0)
    stream: bool | None = False
    tools: list[dict[str, Any]] | None = None
    tool_choice: str | dict[str, Any] | None = None


class ProviderMeResponse(BaseModel):
    provider: ProviderProfile
    recent_jobs: list[ProviderRecentJob] | None = None
