/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models (OpenAI-compatible)
         * @description Returns the merged model catalog plus per-model online provider counts
         *     and USD pricing. Aliased duplicates are collapsed to their canonical
         *     Ollama tag form.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completion
         * @description Routes the request to a capable, non-busy provider. Supports streaming
         *     (SSE) when `stream: true`. Supports function calling (`tools` /
         *     `tool_choice`). Honours `Idempotency-Key` for non-streaming retries.
         */
        post: operations["chatCompletions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage a new renter account (magic-link verification follows) */
        post: operations["renterRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current renter account, recent jobs, and v1 usage summary. */
        get: operations["renterMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quick balance check. */
        get: operations["renterBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Direct sandbox top-up (disabled in production).
         * @description Production traffic must go through the payment flow at
         *     `/api/payments/topup` (not part of this contract). This endpoint
         *     exists for local/sandbox testing only.
         */
        post: operations["renterTopup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renter job history (paginated, status-filtered). */
        get: operations["renterJobsList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/me/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single renter job + billing record. */
        get: operations["renterJobDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/me/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All-time, monthly, and 30-day spending breakdown. */
        get: operations["renterSpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/me/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scoped sub-keys (`dc1-sk-…`) for the calling renter. */
        get: operations["renterListScopedKeys"];
        put?: never;
        /** Mint a scoped sub-key (`dc1-sk-…`). */
        post: operations["renterCreateScopedKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/me/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a scoped sub-key. */
        delete: operations["renterRevokeScopedKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List `dcp_`-prefixed API keys (secret never returned; `key_hint` instead). */
        get: operations["renterListDcpKeys"];
        put?: never;
        /** Mint a `dcp_`-prefixed API key (renter admin only). */
        post: operations["renterCreateDcpKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{id}/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a `dcp_` API key (renter admin only). */
        delete: operations["renterRevokeDcpKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renter balance with the 5 most recent ledger entries (RBAC-protected). */
        get: operations["renterBalanceWithLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated credit/debit ledger. */
        get: operations["renterTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{id}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List renter webhooks (secrets masked). */
        get: operations["renterListWebhooks"];
        put?: never;
        /** Register a webhook for job/balance events. */
        post: operations["renterRegisterWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/renters/{id}/webhooks/{webhookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate a webhook (soft delete). */
        delete: operations["renterDeactivateWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new provider (called by dcp-desktop setup wizard). */
        post: operations["providerRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provider daemon heartbeat (per-id form, REST canonical).
         * @description Provider daemon (dcp-agent) sends every ~30s with current state.
         *     Backend may return queued tasks (e.g. model_preload) for the daemon
         *     to execute. Accepts both legacy and DCP-892 canonical metric names.
         */
        post: operations["providerHeartbeatById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Legacy heartbeat endpoint (api_key in body, HMAC-signed).
         * @description Older daemons post here with `api_key` in the body and an HMAC
         *     signature in `X-DC1-Signature`. Newer daemons should use
         *     `/api/providers/{provider_id}/heartbeat` instead.
         */
        post: operations["providerHeartbeatLegacy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last heartbeat + online/stale/offline status. */
        get: operations["providerLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-provider utilization timeseries. */
        get: operations["providerMetricsTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a GPU benchmark result (assigns tier A/B/C). */
        post: operations["providerSubmitBenchmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider dashboard payload — account, GPU profile, today/week/month earnings, recent jobs. */
        get: operations["providerMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/me/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider aggregate stats + recent completed jobs. */
        get: operations["providerMeMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause this provider (stop accepting new jobs). */
        post: operations["providerPause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume this provider. */
        post: operations["providerResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Renter-scoped job history. */
        get: operations["jobsList"];
        put?: never;
        /**
         * Submit a new job (credit-hold dispatch pipeline).
         * @description Credits are reserved (not immediately debited); actual debit happens
         *     on `PATCH /api/jobs/{job_id}/complete`. Hold is released on
         *     `PATCH /api/jobs/{job_id}/fail`.
         */
        post: operations["jobCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single job with parsed gpu_requirements, queue position, and elapsed time. */
        get: operations["jobGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight job status (polling-friendly). */
        get: operations["jobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE stream of job progress / log lines. */
        get: operations["jobStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job. */
        post: operations["jobCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/manifest.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signed manifest for dcp-agent self-update.
         * @description Returns the safe_commit SHA + rollout percentage. Provider's
         *     self-update cron only checks out the safe_commit if
         *     (sha256(provider_id) mod 100) < rollout_pct.
         */
        get: operations["getAgentManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string | {
                code?: string;
                message?: string;
            };
        };
        SuccessResponse: {
            success: boolean;
        };
        Pagination: {
            page: number;
            limit: number;
            total: number;
            pages: number;
        };
        V1Error: {
            error: {
                message: string;
                /** @description OpenAI-style error type (e.g. invalid_request_error, server_error). */
                type: string;
                code?: string;
                status?: number;
                retryable?: boolean;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        V1ModelUnavailableError: components["schemas"]["V1Error"] & {
            error?: {
                alternatives?: {
                    model: string;
                    reason?: string;
                    provider_count?: number;
                }[];
            };
        };
        ModelList: {
            /** @enum {string} */
            object: "list";
            data: components["schemas"]["Model"][];
        };
        Model: {
            id: string;
            /** @enum {string} */
            object: "model";
            owned_by?: string;
            name?: string;
            description?: string;
            context_length?: number;
            pricing?: components["schemas"]["ModelPricing"];
            architecture?: {
                tokenizer?: string;
                instruct_type?: string;
                modality?: string;
            };
            endpoints?: {
                url?: string;
                type?: string;
            }[];
            provider_priority?: string[];
            display_name?: string;
            context_window?: number;
            parameter_count?: number | null;
        };
        ModelPricing: {
            /** @description USD per token, stringified for precision. */
            prompt_tokens?: string;
            completion_tokens?: string;
            usd_per_minute?: string;
            usd_per_1m_input_tokens?: string;
            usd_per_1m_output_tokens?: string;
        };
        ChatCompletionRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            /** @default 512 */
            max_tokens: number;
            /** @default 0.7 */
            temperature: number;
            /** @default false */
            stream: boolean;
            tools?: {
                [key: string]: unknown;
            }[];
            tool_choice?: string | {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            content?: string | null;
            name?: string;
            tool_call_id?: string;
            tool_calls?: components["schemas"]["ToolCall"][];
        };
        ToolCall: {
            id: string;
            /** @enum {string} */
            type: "function";
            function: {
                name: string;
                arguments: string;
            };
        };
        ChatCompletionResponse: {
            id: string;
            /** @enum {string} */
            object: "chat.completion";
            created: number;
            model: string;
            choices: {
                index?: number;
                message?: components["schemas"]["ChatMessage"];
                finish_reason?: string;
            }[];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
            x_dcp_provider_id?: number;
            x_dcp_routing?: {
                [key: string]: unknown;
            };
        };
        RenterRegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            organization?: string;
            use_case?: string;
            phone?: string;
        };
        RenterRegisterAccepted: {
            success: boolean;
            /** @enum {string} */
            next: "check_email";
            email: string;
            renter_id: number;
            message?: string;
        };
        RenterMeResponse: {
            renter: components["schemas"]["Renter"];
            recent_jobs: components["schemas"]["RenterJobSummary"][];
            v1_usage_summary?: components["schemas"]["RenterV1UsageSummary"];
        };
        Renter: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            organization?: string | null;
            use_case?: string | null;
            phone?: string | null;
            webhook_url?: string | null;
            /** @description Balance in Saudi halala (1 SAR = 100 halala). */
            balance_halala: number;
            total_spent_halala?: number;
            total_jobs?: number;
            /** Format: date-time */
            created_at?: string;
        };
        RenterV1UsageSummary: {
            total_requests?: number;
            prompt_tokens?: number;
            completion_tokens?: number;
            total_tokens?: number;
            total_cost_halala?: number;
        };
        RenterBalanceResponse: {
            balance_halala: number;
            balance_sar: number;
            held_halala: number;
            held_sar: number;
            available_halala: number;
            total_spent_halala: number;
            total_spent_sar: number;
            total_jobs: number;
        };
        /** @description Provide either `amount_halala` (int) or `amount_sar` (float). */
        RenterTopupRequest: {
            amount_halala?: number;
            amount_sar?: number;
        };
        RenterTopupResponse: {
            success: boolean;
            topped_up_halala: number;
            topped_up_sar: number;
            new_balance_halala: number;
            new_balance_sar: number;
        };
        RenterJobSummary: {
            id: number;
            job_id?: string;
            job_type?: string;
            /** @enum {string} */
            status: "pending" | "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            actual_cost_halala?: number | null;
        };
        RenterJobsPage: {
            jobs: components["schemas"]["RenterJobRow"][];
            total: number;
            page: number;
            limit: number;
            pages: number;
        };
        RenterJobRow: {
            job_id?: string;
            template_id?: string | null;
            provider_id?: number | null;
            status?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            cost_halala?: number;
            output_tokens?: number;
            input_tokens?: number | null;
        };
        RenterSpendingResponse: {
            all_time: {
                total_jobs: number;
                total_halala: number;
                total_sar: number;
            };
            monthly: {
                /** @description YYYY-MM. */
                month: string;
                jobs: number;
                total_halala: number;
            }[];
            last_30_days: {
                /** Format: date */
                date: string;
                jobs: number;
                total_halala: number;
            }[];
        };
        ScopedKeyCreateRequest: {
            label?: string;
            /**
             * @default [
             *       "inference"
             *     ]
             */
            scopes: ("inference" | "jobs.read" | "balance.read" | "admin")[];
            /** Format: date-time */
            expires_at?: string;
            org_role?: string;
        };
        ScopedApiKey: {
            id: string;
            label?: string | null;
            scopes: string[];
            org_id?: string | null;
            org_role?: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            created_at: string;
            revoked: boolean;
        };
        ScopedApiKeyMinted: components["schemas"]["ScopedApiKey"] & {
            /** @description The full secret. Returned exactly once; persisted only as a hash. */
            key: string;
        };
        DcpKeyCreateRequest: {
            label?: string;
            /**
             * @default [
             *       "inference"
             *     ]
             */
            permissions: ("inference" | "jobs.read" | "balance.read")[];
            org_role?: string;
        };
        DcpKeyMinted: {
            keyId: string;
            /** @description Returned exactly once. */
            key: string;
            label?: string | null;
            permissions: string[];
            org_id?: string | null;
            org_role?: string;
            /** Format: date-time */
            created_at: string;
        };
        RenterDcpKeyListItem: {
            keyId: string;
            label?: string | null;
            permissions: string[];
            /** @description Format: `dcp_...XXXX` (last 4 chars only). */
            key_hint: string;
            org_id?: string | null;
            org_role?: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            created_at: string;
            revoked: boolean;
        };
        RenterBalanceWithLedger: {
            balance_sar: number;
            balance_halala: number;
            balance_usd?: number;
            /** Format: date-time */
            last_topup_at?: string | null;
            total_spent_sar?: number;
            recent_transactions: components["schemas"]["LedgerEntry"][];
        };
        LedgerEntry: {
            id: string;
            /** @enum {string} */
            direction: "credit" | "debit";
            amount_halala: number;
            amount_sar?: number;
            description?: string;
            job_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        LedgerPage: {
            entries: components["schemas"]["LedgerEntry"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        RenterWebhook: {
            id: string;
            /** Format: uri */
            url: string;
            events: ("job.completed" | "job.failed" | "balance.low")[];
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        RenterWebhookCreate: {
            /**
             * Format: uri
             * @description HTTPS-only, port 443, public host (SSRF-checked).
             */
            url: string;
            /** @description HMAC signing secret (>= 16 chars). */
            secret: string;
            events?: ("job.completed" | "job.failed" | "balance.low")[];
        };
        ProviderRegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            gpu_model: string;
            /** @description Normalized OS (linux/windows/macos). */
            os: string;
            phone?: string;
            location?: string;
            resource_spec?: {
                [key: string]: unknown;
            } | string;
        };
        ProviderRegisterResponse: {
            success: boolean;
            provider_id: number;
            /** @description `dcp-provider-…` — keep secret. */
            api_key: string;
            /** @description Canonical setup download path (relative). */
            installer_url: string;
            message?: string;
        };
        /**
         * @description Per-id heartbeat. Auth is `X-Provider-Key` (or bearer). Body accepts
         *     both legacy field names and the DCP-892 canonical names.
         */
        HeartbeatRequest: {
            gpu_utilization_pct?: number;
            /** @description Legacy alias for gpu_utilization_pct. */
            gpu_utilization?: number;
            vram_used_mb?: number;
            /** @description Legacy alias for vram_used_mb. */
            vram_used?: number;
            vram_total_mb?: number;
            /** @description Legacy alias for vram_total_mb. */
            vram_total?: number;
            active_jobs?: number;
            /** @description Legacy alias. */
            jobs_active?: number;
            /** @description Legacy alias. */
            jobs_running?: number;
            uptime_seconds?: number;
            /** @description Currently loaded model identifier. */
            model_loaded?: string;
        } & {
            [key: string]: unknown;
        };
        HeartbeatLegacyRequest: {
            api_key: string;
            gpu_status?: {
                [key: string]: unknown;
            };
            gpu_info?: components["schemas"]["GpuInfo"];
            uptime?: number;
            provider_ip?: string;
            provider_hostname?: string;
            peer_id?: string;
            cached_models?: string[];
            resource_spec?: {
                [key: string]: unknown;
            };
            /** Format: uri */
            vllm_endpoint_url?: string;
            vllm_models?: string[];
            wg_mesh_ip?: string;
            wg_health?: {
                [key: string]: unknown;
            };
            task_updates?: {
                [key: string]: unknown;
            }[];
            version?: string;
            /** @enum {string} */
            status?: "online" | "busy" | "paused" | "error";
            models?: components["schemas"]["ModelStatus"][];
        } & {
            [key: string]: unknown;
        };
        HeartbeatResponse: {
            ok?: boolean;
            success?: boolean;
            provider_id?: number | string;
            status?: string;
            /** Format: date-time */
            timestamp?: string;
            uptime_seconds?: number;
            model_loaded?: string;
            pending_tasks?: components["schemas"]["PendingTask"][];
        };
        PendingTask: {
            task_id: string;
            /** @enum {string} */
            task_type: "model_preload" | "model_unload" | "restart" | "config_reload" | "pull_model";
            params?: {
                [key: string]: unknown;
            };
        };
        GpuInfo: {
            /** @enum {string} */
            vendor: "nvidia" | "amd" | "apple" | "intel";
            count: number;
            total_vram_gb: number;
            cards?: {
                model?: string;
                vram_gb?: number;
                compute_capability?: string;
            }[];
        };
        ModelStatus: {
            /** @example qwen3.6-27b-mtp */
            alias: string;
            /** @enum {string} */
            engine?: "ollama" | "vllm" | "llamacpp";
            ready: boolean;
            port?: number;
            context_window?: number;
        };
        ProviderLivenessResponse: {
            provider_id: number | string;
            /** @enum {string} */
            liveness_status: "online" | "stale" | "offline";
            /** Format: date-time */
            last_heartbeat?: string | null;
            heartbeat_age_seconds?: number | null;
        };
        ProviderMetricsTimeseries: {
            provider_id: string;
            /** @enum {string} */
            period: "1h" | "6h" | "24h" | "7d";
            /** Format: date-time */
            since: string;
            count: number;
            metrics: components["schemas"]["ProviderMetricsRow"][];
        };
        ProviderMetricsRow: {
            /** Format: date-time */
            recorded_at: string;
            gpu_utilization_pct?: number | null;
            vram_used_mb?: number | null;
            active_jobs?: number | null;
        };
        ProviderBenchmarkRequest: {
            gpu_model: string;
            vram_gb: number;
            tflops: number;
            bandwidth_gbps: number;
            tokens_per_sec: number;
            /**
             * @description Optional; auto-assigned by tflops + vram if absent.
             * @enum {string}
             */
            tier?: "A" | "B" | "C";
        };
        ProviderBenchmarkResponse: {
            success: boolean;
            provider_id: number | string;
            gpu_model: string;
            /** @enum {string} */
            tier: "A" | "B" | "C";
            /** Format: date-time */
            timestamp: string;
            message?: string;
        };
        ProviderMeResponse: {
            provider: components["schemas"]["ProviderProfile"];
            recent_jobs?: components["schemas"]["ProviderRecentJob"][];
        };
        ProviderProfile: {
            id: number;
            name: string;
            /** @enum {string} */
            status: "registered" | "online" | "offline" | "paused" | "connected" | "error";
            gpu_model: string;
            gpu_vram_mib?: number;
            gpu_count_reported?: number;
            gpu_compute_capability?: string | null;
            gpu_cuda_version?: string | null;
            vram_mb?: number;
            gpu_count?: number;
            supported_compute_types?: ("inference" | "training" | "rendering")[];
            /** @enum {string} */
            gpu_profile_source?: "daemon" | "manual";
            /** Format: date-time */
            gpu_profile_updated_at?: string | null;
            auto_detected?: boolean;
            resource_spec?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            last_heartbeat?: string | null;
            daemon_version?: string | null;
            run_mode?: string;
            scheduled_start?: string;
            scheduled_end?: string;
            wallet_address?: string | null;
            /** Format: date-time */
            wallet_address_updated_at?: string | null;
            gpu_usage_cap_pct?: number;
            vram_reserve_gb?: number;
            temp_limit_c?: number;
            is_paused?: boolean;
            /** @enum {string} */
            approval_status?: "pending" | "approved" | "rejected";
            /** Format: date-time */
            approved_at?: string | null;
            rejected_reason?: string | null;
            total_earnings_halala?: number;
            total_jobs?: number;
            uptime_percent?: number;
            gpu_metrics?: {
                utilization_pct?: number;
                vram_used_mib?: number;
                temperature_c?: number;
            };
            today_earnings_halala?: number;
            week_earnings_halala?: number;
            month_earnings_halala?: number;
            active_job?: components["schemas"]["ProviderActiveJob"] | null;
        };
        ProviderActiveJob: {
            id?: number;
            job_id?: string;
            job_type?: string;
            /** Format: date-time */
            started_at?: string;
            cost_halala?: number;
        };
        ProviderRecentJob: {
            id?: number;
            job_id?: string;
            job_type?: string;
            model?: string | null;
            status?: string;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            actual_cost_halala?: number | null;
            provider_earned_halala?: number | null;
            dc1_fee_halala?: number | null;
        };
        ProviderMeMetricsResponse: {
            provider_id: number;
            gpu_model?: string | null;
            stats: components["schemas"]["ProviderStats"];
            recent_jobs?: components["schemas"]["ProviderRecentJob"][];
        };
        ProviderStats: {
            jobs_completed: number;
            jobs_failed: number;
            total_compute_minutes: number;
            earnings_halala: number;
            earnings_sar: number;
            uptime_hours_last_7d: number;
            avg_job_duration_minutes: number;
        };
        JobCreateRequest: {
            /**
             * @description Required unless `template_id` resolves a job_type. Allowed values
             *     are enforced server-side (training/inference/render variants).
             */
            job_type?: string;
            /** @description Docker template id; supplies job_type defaults. */
            template_id?: string;
            duration_minutes: number;
            gpu_requirements?: {
                min_vram_gb?: number;
                gpu_type?: string;
            };
            params?: {
                [key: string]: unknown;
            };
            /**
             * @default standard
             * @enum {string}
             */
            pricing_class: "standard" | "priority" | "economy";
            model?: string;
            /** @description Optional sticky-routing hint. */
            provider_id?: number;
        };
        JobCreateResponse: {
            success: boolean;
            job: components["schemas"]["Job"];
            dispatch: components["schemas"]["JobDispatchInfo"];
            idempotent?: boolean;
        };
        JobDispatchInfo: {
            assigned: boolean;
            queued: boolean;
            hold_id?: string | null;
            provider?: null | {
                id?: number;
                name?: string;
            };
        };
        Job: {
            id?: number;
            job_id: string;
            job_type?: string;
            model?: string | null;
            /** @enum {string} */
            status: "pending" | "queued" | "running" | "completed" | "failed" | "cancelled";
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            duration_minutes?: number | null;
            actual_duration_minutes?: number | null;
            cost_halala?: number;
            actual_cost_halala?: number | null;
            prompt_tokens?: number | null;
            completion_tokens?: number | null;
            provider_id?: number | null;
            renter_id?: number;
            pricing_class?: string;
            gpu_requirements?: null | {
                [key: string]: unknown;
            };
            /** @description Present only when status = queued. */
            queue_position?: number;
            elapsed_sec?: number | null;
            tokens_used?: number | null;
            cost_usd?: number | null;
            /** Format: date-time */
            refunded_at?: string | null;
        };
        JobWithBilling: components["schemas"]["Job"] & {
            provider_name?: string | null;
            billing_id?: string | null;
            gross_cost_halala?: number | null;
            platform_fee_halala?: number | null;
            provider_earning_halala?: number | null;
            currency?: string;
            billing_status?: string | null;
            token_count?: number | null;
            duration_ms?: number | null;
        };
        JobsListResponse: {
            total: number;
            limit: number;
            offset: number;
            jobs: components["schemas"]["JobListRow"][];
        };
        JobListRow: {
            id?: number;
            job_id?: string;
            job_type?: string;
            template_name?: string | null;
            gpu_model?: string | null;
            status?: string;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            duration_seconds?: number | null;
            tokens_used?: number | null;
            /** @description SAR formatted to 2 decimals. */
            cost_sar?: string;
            refunded?: boolean;
        };
        JobStatusResponse: {
            job_id: string;
            status: string;
            tokens_generated?: number;
            elapsed_seconds?: number | null;
            estimated_cost_usd?: number | null;
            provider_online?: boolean;
        };
        InsufficientBalanceError: {
            error: string;
            balance_halala?: number;
            required_halala?: number;
            shortfall_halala?: number;
            available_halala?: number;
            docs?: string;
        };
        AgentManifest: {
            safe_commit: string;
            rollout_pct: number;
            /** Format: date-time */
            published_at: string;
            /**
             * @description Optional minimum semver tag.
             * @example v0.6.0
             */
            min_tag?: string;
        };
    };
    responses: {
        /** @description Missing or invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request body or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller is authenticated but not allowed to access this resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid API key. */
        V1Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["V1Error"];
            };
        };
        /** @description Invalid request body. */
        V1BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["V1Error"];
            };
        };
    };
    parameters: {
        PageParam: number;
        LimitParam: number;
        /** @description Numeric renter id. */
        RenterIdParam: number;
        /** @description Either the numeric primary key or the `job-<ts>-<rand>` external id. */
        JobIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            /** @description Catalog temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1Error"];
                };
            };
        };
    };
    chatCompletions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for non-streaming requests; cached for ~5 min. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /**
             * @description Completion response. Streaming requests return `text/event-stream`
             *     with OpenAI-format chunks; non-streaming returns the JSON body.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["V1BadRequest"];
            401: components["responses"]["V1Unauthorized"];
            /** @description Insufficient balance */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1Error"];
                };
            };
            /** @description Model not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1Error"];
                };
            };
            /**
             * @description No capable provider available, or all capable providers busy.
             *     Includes Retry-After header and (when available) a list of
             *     suggested alternative models.
             */
            503: {
                headers: {
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V1ModelUnavailableError"];
                };
            };
        };
    };
    renterRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenterRegisterRequest"];
            };
        };
        responses: {
            /** @description Renter staged; magic link sent for verification. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterRegisterAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Renter with this email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renterMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Renter snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterMeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    renterBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterBalanceResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    renterTopup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenterTopupRequest"];
            };
        };
        responses: {
            /** @description Top-up applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterTopupResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Direct top-up disabled in production. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    renterJobsList: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                limit?: components["parameters"]["LimitParam"];
                status?: "completed" | "failed" | "running" | "pending" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterJobsPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    renterJobDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job with attached billing line item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["JobWithBilling"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    renterSpending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spending rollups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterSpendingResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    renterListScopedKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scoped key list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: components["schemas"]["ScopedApiKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    renterCreateScopedKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopedKeyCreateRequest"];
            };
        };
        responses: {
            /** @description New scoped key (`key` returned once, never again). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopedApiKeyMinted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Too many active sub-keys. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renterRevokeScopedKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** Format: date-time */
                        revoked_at: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    renterListDcpKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key list with hints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: components["schemas"]["RenterDcpKeyListItem"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    renterCreateDcpKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DcpKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Key minted; `key` returned once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DcpKeyMinted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Too many active keys for this renter. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renterRevokeDcpKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    renterBalanceWithLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance + recent ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterBalanceWithLedger"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    renterTransactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                direction?: "credit" | "debit";
            };
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPage"];
                };
            };
        };
    };
    renterListWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        webhooks: components["schemas"]["RenterWebhook"][];
                    };
                };
            };
        };
    };
    renterRegisterWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenterWebhookCreate"];
            };
        };
        responses: {
            /** @description Webhook registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenterWebhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Webhook quota exceeded (max 5 per renter). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renterDeactivateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Numeric renter id. */
                id: components["parameters"]["RenterIdParam"];
                webhookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        id: string;
                        /** @enum {boolean} */
                        active: false;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    providerRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderRegisterRequest"];
            };
        };
        responses: {
            /** @description Provider created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRegisterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Provider with this email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    providerHeartbeatById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Heartbeat acknowledged; optional task queue returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Provider not approved. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    providerHeartbeatLegacy: {
        parameters: {
            query?: never;
            header?: {
                "X-DC1-Signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatLegacyRequest"];
            };
        };
        responses: {
            /** @description Heartbeat accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    providerLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderLivenessResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    providerMetricsTimeseries: {
        parameters: {
            query?: {
                period?: "1h" | "6h" | "24h" | "7d";
            };
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeseries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMetricsTimeseries"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    providerSubmitBenchmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderBenchmarkRequest"];
            };
        };
        responses: {
            /** @description Benchmark recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderBenchmarkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    providerMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMeResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    providerMeMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMeMetricsResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    providerPause: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Provider API key. */
                    key: string;
                };
            };
        };
        responses: {
            /** @description Paused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        status: "paused";
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    providerResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    key: string;
                };
            };
        };
        responses: {
            /** @description Resumed; status is `online` if heartbeat is recent, else `connected`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        status: "online" | "connected";
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    jobsList: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    jobCreate: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection; cached for 5 minutes. */
                "X-Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Job created and dispatched (or queued). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Insufficient balance. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsufficientBalanceError"];
                };
            };
            /** @description No providers online. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    jobGet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either the numeric primary key or the `job-<ts>-<rand>` external id. */
                job_id: components["parameters"]["JobIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        job: components["schemas"]["Job"];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    jobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either the numeric primary key or the `job-<ts>-<rand>` external id. */
                job_id: components["parameters"]["JobIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    jobStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either the numeric primary key or the `job-<ts>-<rand>` external id. */
                job_id: components["parameters"]["JobIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    jobCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Either the numeric primary key or the `job-<ts>-<rand>` external id. */
                job_id: components["parameters"]["JobIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAgentManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current manifest. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentManifest"];
                };
            };
        };
    };
}
